### ISSUE TITLE
Do you remember AFDateHelper version?

### ISSUE THREAD

**Issue by vietstone-ng** [icanzilb/RealmNotificationExample#1]
Hi,
I tried to run the project with Xcode 7.3.1, but it doesn't run, and find that AFDateHelper version is not matched. Do you remember the version, so I can make change in Podfile?
Thank you

**Comment by icanzilb** [comment]
not really, but if you want to dig into it just stride the release list of AFDateHelper and find which version was the current one last May when I wrote the article :)

**Comment by icanzilb** [comment]
@vietstone I update the repo to Swift 3 and latest pod version, you can check it out again 👍

**Comment by vietstone-ng** [comment]
wow, thank you @icanzilb !!!
